2021-09-18 20:17:50,697 INFO    MainThread:161413 [internal.py:wandb_internal():91] W&B internal server running at pid: 161413, started at: 2021-09-18 20:17:50.696113
2021-09-18 20:17:50,698 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: check_version
2021-09-18 20:17:50,698 INFO    WriterThread:161413 [datastore.py:open_for_write():80] open: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/run-4o7h6zpm.wandb
2021-09-18 20:17:50,700 DEBUG   SenderThread:161413 [sender.py:send():179] send: header
2021-09-18 20:17:50,701 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: check_version
2021-09-18 20:17:50,730 DEBUG   SenderThread:161413 [sender.py:send():179] send: run
2021-09-18 20:17:50,792 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:17:50,792 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:17:51,995 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:17:51,995 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:17:54,510 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:17:54,510 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:17:54,510 ERROR   SenderThread:161413 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.wandb.ai/graphql
2021-09-18 20:17:59,160 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:17:59,160 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:08,466 INFO    SenderThread:161413 [dir_watcher.py:__init__():168] watching files in: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files
2021-09-18 20:18:08,466 INFO    SenderThread:161413 [sender.py:_start_run_threads():719] run started: 4o7h6zpm with start time 1632010670
2021-09-18 20:18:08,466 DEBUG   SenderThread:161413 [sender.py:send():179] send: summary
2021-09-18 20:18:08,467 INFO    SenderThread:161413 [sender.py:_save_file():841] saving file wandb-summary.json with policy end
2021-09-18 20:18:08,468 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: run_start
2021-09-18 20:18:09,469 INFO    Thread-8  :161413 [dir_watcher.py:_on_file_created():216] file/dir created: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/wandb-summary.json
2021-09-18 20:18:09,636 DEBUG   HandlerThread:161413 [meta.py:__init__():39] meta init
2021-09-18 20:18:09,636 DEBUG   HandlerThread:161413 [meta.py:__init__():53] meta init done
2021-09-18 20:18:09,636 DEBUG   HandlerThread:161413 [meta.py:probe():210] probe
2021-09-18 20:18:09,642 DEBUG   HandlerThread:161413 [meta.py:_save_pip():57] save pip
2021-09-18 20:18:09,643 DEBUG   HandlerThread:161413 [meta.py:_save_pip():71] save pip done
2021-09-18 20:18:09,643 DEBUG   HandlerThread:161413 [meta.py:probe():252] probe done
2021-09-18 20:18:09,645 DEBUG   SenderThread:161413 [sender.py:send():179] send: files
2021-09-18 20:18:09,645 INFO    SenderThread:161413 [sender.py:_save_file():841] saving file wandb-metadata.json with policy now
2021-09-18 20:18:09,653 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: stop_status
2021-09-18 20:18:09,653 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: stop_status
2021-09-18 20:18:09,701 ERROR   Thread-11 :161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:09,701 ERROR   Thread-11 :161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:09,723 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:09,723 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:10,469 INFO    Thread-8  :161413 [dir_watcher.py:_on_file_created():216] file/dir created: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/output.log
2021-09-18 20:18:10,469 INFO    Thread-8  :161413 [dir_watcher.py:_on_file_created():216] file/dir created: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/wandb-metadata.json
2021-09-18 20:18:10,470 INFO    Thread-8  :161413 [dir_watcher.py:_on_file_created():216] file/dir created: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/requirements.txt
2021-09-18 20:18:10,899 ERROR   Thread-11 :161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:10,900 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:20,767 ERROR   Thread-11 :161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:20,767 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:20,767 ERROR   Thread-11 :161413 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.wandb.ai/graphql
2021-09-18 20:18:20,768 ERROR   SenderThread:161413 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.wandb.ai/graphql
2021-09-18 20:18:23,508 INFO    Thread-11 :161413 [upload_job.py:push():137] Uploaded file /tmp/3288851.1.gpu_ded.q/tmp0_vgnr1twandb/3vwjv5np-wandb-metadata.json
2021-09-18 20:18:37,954 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: stop_status
2021-09-18 20:18:37,954 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: stop_status
2021-09-18 20:18:38,009 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:38,010 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:39,142 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:39,142 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:41,697 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:41,698 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:41,698 ERROR   SenderThread:161413 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.wandb.ai/graphql
2021-09-18 20:18:46,246 DEBUG   SenderThread:161413 [sender.py:send():179] send: stats
2021-09-18 20:18:53,203 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:18:53,203 DEBUG   SenderThread:161413 [sender.py:send():179] send: telemetry
2021-09-18 20:18:53,264 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:53,264 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:54,373 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:54,373 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:56,715 ERROR   SenderThread:161413 [internal_api.py:execute():130] 429 response executing GraphQL.
2021-09-18 20:18:56,716 ERROR   SenderThread:161413 [internal_api.py:execute():131] {"error":"rate limit exceeded"}

2021-09-18 20:18:56,716 ERROR   SenderThread:161413 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 133, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.wandb.ai/graphql
2021-09-18 20:18:58,304 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:01,278 DEBUG   SenderThread:161413 [sender.py:send():179] send: exit
2021-09-18 20:19:01,278 INFO    SenderThread:161413 [sender.py:send_exit():287] handling exit code: 1
2021-09-18 20:19:01,278 INFO    SenderThread:161413 [sender.py:send_exit():295] send defer
2021-09-18 20:19:01,278 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:01,278 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:01,279 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:01,279 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 0
2021-09-18 20:19:01,279 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:01,279 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 0
2021-09-18 20:19:01,279 INFO    SenderThread:161413 [sender.py:transition_state():308] send defer: 1
2021-09-18 20:19:01,279 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:01,279 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 1
2021-09-18 20:19:01,357 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:01,357 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 1
2021-09-18 20:19:01,357 INFO    SenderThread:161413 [sender.py:transition_state():308] send defer: 2
2021-09-18 20:19:01,357 DEBUG   SenderThread:161413 [sender.py:send():179] send: stats
2021-09-18 20:19:01,358 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:01,360 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 2
2021-09-18 20:19:01,360 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:01,360 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 2
2021-09-18 20:19:01,360 INFO    SenderThread:161413 [sender.py:transition_state():308] send defer: 3
2021-09-18 20:19:01,360 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:01,361 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 3
2021-09-18 20:19:01,361 DEBUG   SenderThread:161413 [sender.py:send():179] send: summary
2021-09-18 20:19:01,361 INFO    SenderThread:161413 [sender.py:_save_file():841] saving file wandb-summary.json with policy end
2021-09-18 20:19:01,361 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:01,361 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 3
2021-09-18 20:19:01,361 INFO    SenderThread:161413 [sender.py:transition_state():308] send defer: 4
2021-09-18 20:19:01,361 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:01,361 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 4
2021-09-18 20:19:01,362 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:01,362 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 4
2021-09-18 20:19:01,362 INFO    SenderThread:161413 [sender.py:transition_state():308] send defer: 5
2021-09-18 20:19:01,362 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:01,362 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 5
2021-09-18 20:19:01,362 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:01,362 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 5
2021-09-18 20:19:01,362 INFO    SenderThread:161413 [dir_watcher.py:finish():282] shutting down directory watcher
2021-09-18 20:19:01,383 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:01,478 INFO    SenderThread:161413 [dir_watcher.py:_on_file_modified():229] file/dir modified: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/config.yaml
2021-09-18 20:19:01,478 INFO    SenderThread:161413 [dir_watcher.py:_on_file_modified():229] file/dir modified: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/wandb-summary.json
2021-09-18 20:19:01,479 INFO    SenderThread:161413 [dir_watcher.py:finish():312] scan: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files
2021-09-18 20:19:01,479 INFO    SenderThread:161413 [dir_watcher.py:finish():318] scan save: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/wandb-metadata.json wandb-metadata.json
2021-09-18 20:19:01,479 INFO    SenderThread:161413 [dir_watcher.py:finish():318] scan save: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/config.yaml config.yaml
2021-09-18 20:19:01,479 INFO    SenderThread:161413 [dir_watcher.py:finish():318] scan save: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/requirements.txt requirements.txt
2021-09-18 20:19:01,479 INFO    SenderThread:161413 [dir_watcher.py:finish():318] scan save: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/wandb-summary.json wandb-summary.json
2021-09-18 20:19:01,479 INFO    SenderThread:161413 [dir_watcher.py:finish():318] scan save: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/output.log output.log
2021-09-18 20:19:01,485 INFO    SenderThread:161413 [sender.py:transition_state():308] send defer: 6
2021-09-18 20:19:01,485 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:01,490 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:01,490 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 6
2021-09-18 20:19:01,491 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:01,491 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 6
2021-09-18 20:19:01,491 INFO    SenderThread:161413 [file_pusher.py:finish():177] shutting down file pusher
2021-09-18 20:19:01,602 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:01,602 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:01,706 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:01,706 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:01,783 INFO    Thread-12 :161413 [upload_job.py:push():137] Uploaded file /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/config.yaml
2021-09-18 20:19:01,785 INFO    Thread-14 :161413 [upload_job.py:push():137] Uploaded file /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/wandb-summary.json
2021-09-18 20:19:01,808 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:01,809 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:01,819 INFO    Thread-13 :161413 [upload_job.py:push():137] Uploaded file /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/files/requirements.txt
2021-09-18 20:19:01,913 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:01,913 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:02,018 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:02,018 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:02,019 INFO    Thread-7  :161413 [sender.py:transition_state():308] send defer: 7
2021-09-18 20:19:02,020 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:02,020 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 7
2021-09-18 20:19:02,020 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:02,020 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 7
2021-09-18 20:19:02,120 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:02,122 INFO    SenderThread:161413 [sender.py:transition_state():308] send defer: 8
2021-09-18 20:19:02,123 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:02,123 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:02,123 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 8
2021-09-18 20:19:02,123 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:02,123 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 8
2021-09-18 20:19:02,123 INFO    SenderThread:161413 [sender.py:transition_state():308] send defer: 9
2021-09-18 20:19:02,124 DEBUG   SenderThread:161413 [sender.py:send():179] send: final
2021-09-18 20:19:02,124 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: defer
2021-09-18 20:19:02,124 DEBUG   SenderThread:161413 [sender.py:send():179] send: footer
2021-09-18 20:19:02,124 INFO    HandlerThread:161413 [handler.py:handle_request_defer():141] handle defer: 9
2021-09-18 20:19:02,124 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: defer
2021-09-18 20:19:02,124 INFO    SenderThread:161413 [sender.py:send_request_defer():304] handle sender defer: 9
2021-09-18 20:19:02,224 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: poll_exit
2021-09-18 20:19:02,225 DEBUG   SenderThread:161413 [sender.py:send_request():193] send_request: poll_exit
2021-09-18 20:19:02,225 INFO    SenderThread:161413 [file_pusher.py:join():182] waiting for file pusher
2021-09-18 20:19:02,226 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: get_summary
2021-09-18 20:19:02,227 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: sampled_history
2021-09-18 20:19:02,228 DEBUG   HandlerThread:161413 [handler.py:handle_request():124] handle_request: shutdown
2021-09-18 20:19:02,228 INFO    HandlerThread:161413 [handler.py:finish():638] shutting down handler
2021-09-18 20:19:03,124 INFO    WriterThread:161413 [datastore.py:close():288] close: /grid/koo/home/toneyan/profile/QuantPred/wandb/run-20210918_201750-4o7h6zpm/run-4o7h6zpm.wandb
2021-09-18 20:19:03,225 INFO    SenderThread:161413 [sender.py:finish():945] shutting down sender
2021-09-18 20:19:03,225 INFO    SenderThread:161413 [file_pusher.py:finish():177] shutting down file pusher
2021-09-18 20:19:03,225 INFO    SenderThread:161413 [file_pusher.py:join():182] waiting for file pusher
2021-09-18 20:19:03,227 INFO    MainThread:161413 [internal.py:handle_exit():78] Internal process exited
